[package]
name = "mu"
version = "0.1.0"
edition = "2024"

[dependencies]
#color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"

[profile.release]
opt-level = 'z' # Optimize for size
lto = true
strip = true
codegen-units = 1
panic = "abort"